Getting rid of `unused parameter ‘lest_env’ [-Werror=unused-parameter]` (#64)
* Getting rid of `unused parameter ‘lest_env’ [-Werror=unused-parameter]` 

In the test-file `lest_cpp03.hpp`, the parameter `lest_env` may be not used in the expansion of the macro `lest_CASE`.

The full warning:
In file included from build/optional-lite-src/test/optional-main.t.h:18,
                 from build/optional-lite-src/test/optional-main.t.cpp:8:
build/optional-lite-src/test/optional-main.t.cpp: In function ‘void __lest_function__26(lest::env&)’:
build/optional-lite-src/test/lest_cpp03.hpp:266:43: error: unused parameter ‘lest_env’ [-Werror=unused-parameter]
     static void lest_FUNCTION(lest::env & lest_env)
                               ~~~~~~~~~~~~^~~~~~~~
build/optional-lite-src/test/optional-main.t.h:22:22: note: in expansion of macro ‘lest_CASE’
 #define CASE( name ) lest_CASE( specification(), name )
                      ^~~~~~~~~
build/optional-lite-src/test/optional-main.t.cpp:26:1: note: in expansion of macro ‘CASE’
 CASE( "__cplusplus" "[.stdc++]" )

* Fixed bug in else case, where ARG was not given