Change EXPECT() macros to use "do {...} while( false )" iteration statement as in CATCH [1]
It is to not let the implementation of lest be dictated by preventing a VC12/VC13 bug [2].
This lays the burden of preventing the bug by the user of lest.

[1] See remark in issue 315: Catch is susceptible to VC12 bug: do-while loop within range-based-for fails to compile, https://github.com/philsquared/Catch/issues/315#issuecomment-54049380.

[2] Syntax error C2317 for range-for with try-catch statement, https://connect.microsoft.com/VisualStudio/feedbackdetail/view/874705.